// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mYX5_kq2GczV-dp2XjiYpnIOx0206sg',
    appId: '1:816941454020:web:08fae4671d240bd934ef91',
    messagingSenderId: '816941454020',
    projectId: 'jobsque-b59dc',
    authDomain: 'jobsque-b59dc.firebaseapp.com',
    storageBucket: 'jobsque-b59dc.appspot.com',
    measurementId: 'G-PEPBCVX07T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbjnKbMBX3BIUMIz6C8GBQ4otZ-N_ilfg',
    appId: '1:816941454020:android:7a5e3c600089c70d34ef91',
    messagingSenderId: '816941454020',
    projectId: 'jobsque-b59dc',
    storageBucket: 'jobsque-b59dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEeZScIrh0zeV3rXGui1KeZkKpOM5aKDg',
    appId: '1:816941454020:ios:76b9a707b8bd4e3f34ef91',
    messagingSenderId: '816941454020',
    projectId: 'jobsque-b59dc',
    storageBucket: 'jobsque-b59dc.appspot.com',
    iosClientId: '816941454020-mi4tbc6gaed4ntanii8vtn32mhrsgl2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEeZScIrh0zeV3rXGui1KeZkKpOM5aKDg',
    appId: '1:816941454020:ios:57c6cd60a124725734ef91',
    messagingSenderId: '816941454020',
    projectId: 'jobsque-b59dc',
    storageBucket: 'jobsque-b59dc.appspot.com',
    iosClientId: '816941454020-5kfu07vhc6fb1rp6vb6h7400o8dai8an.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsque.RunnerTests',
  );
}
